import { StyleSheet } from "@react-pdf/renderer";

export const PAGE_MARGIN = 54;

export const styles = StyleSheet.create({
  page: {
    paddingTop: PAGE_MARGIN,
    paddingBottom: PAGE_MARGIN,
    paddingLeft: PAGE_MARGIN,
    paddingRight: PAGE_MARGIN,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#1E1E1E",
  },
  coverPage: {
    paddingTop: PAGE_MARGIN,
    paddingBottom: PAGE_MARGIN,
    paddingLeft: PAGE_MARGIN,
    paddingRight: PAGE_MARGIN,
    fontFamily: "Helvetica",
    color: "#1E1E1E",
    alignItems: "center",
  },
  letterheadLogo: { width: 72, height: 72, marginBottom: 12, objectFit: "contain" },
  companyName: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: "#1E1E1E",
    textAlign: "center",
    marginBottom: 4,
  },
  companyAddress: { fontSize: 10, color: "#525252", textAlign: "center" },
  coverTitle: {
    fontSize: 28,
    fontFamily: "Helvetica-Bold",
    color: "#1E1E1E",
    textAlign: "center",
    marginBottom: 12,
  },
  coverDescription: {
    fontSize: 12,
    color: "#3F3F3F",
    lineHeight: 1.5,
    marginBottom: 24,
    textAlign: "center",
    maxWidth: "85%",
  },
  coverPhotoBox: {
    width: "100%",
    height: 252,
    marginBottom: 24,
  },
  coverPhoto: { width: "100%", height: "100%", objectFit: "contain" },
  coverMeta: { marginTop: 16, alignItems: "center" },
  coverMetaLine: { fontSize: 10, color: "#525252", marginBottom: 4, textAlign: "center" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    marginBottom: 16,
  },
  headerTitle: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#1E1E1E" },
  headerDate: { fontSize: 10, color: "#525252" },
  footer: {
    position: "absolute",
    bottom: 18,
    left: PAGE_MARGIN,
    right: PAGE_MARGIN,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: { fontSize: 9, color: "#525252", flex: 1 },
  footerCenter: { fontSize: 9, color: "#525252", flex: 1, textAlign: "center" },
  footerRight: { flex: 1, alignItems: "flex-end" },
  footerLogo: { height: 24, width: 24, objectFit: "contain" },
  sectionHeader: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: "#1E1E1E",
    marginBottom: 6,
  },
  sectionSummary: { fontSize: 11, color: "#3F3F3F", lineHeight: 1.5, marginBottom: 14 },
  grid: { flexDirection: "row", flexWrap: "wrap" },
  cell: {
    width: "48%",
    marginRight: "2%",
    marginBottom: 16,
  },
  cellPhotoBox: {
    width: "100%",
    height: 168,
    marginBottom: 6,
  },
  cellPhoto: { width: "100%", height: "100%", objectFit: "contain" },
  cellPhotoMissing: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F0EDEA",
  },
  cellCaption: { fontSize: 11, fontFamily: "Helvetica-Bold", color: "#1E1E1E", marginBottom: 2 },
  cellDescription: { fontSize: 9, color: "#525252", lineHeight: 1.4 },
});
