// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/annotation-verify/FullSizeViewerSim.tsx": () => import("../components/mockups/annotation-verify/FullSizeViewerSim.tsx"),
  "./components/mockups/annotation-verify/ThumbnailBeforeAfter.tsx": () => import("../components/mockups/annotation-verify/ThumbnailBeforeAfter.tsx")
};
